import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ReactNode } from "react";
import { useRouter } from "next/router";
import HeaderLogo from "src/images/SWapiLogo.png";
import ArrowBack from "src/images/ArrowLeft.svg"

import styles from "@/styles/Home.module.css";

interface Props {
  children: ReactNode;
}

export default function Layout({ children }: Props) {
  const { pathname } = useRouter();
  console.log(pathname);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.mainHeader}>
        <Image src={HeaderLogo} alt="header" />
      </header>
      {pathname !== '/' &&
        <header className={styles.backButtonWrapper}>
          <button className={styles.backButton}>
            <Link href={"/"}>
              <Image className={styles.arrow} src={ArrowBack} alt="arrow-back" />
            </Link>
          </button>
        </header>}
      {children}
    </>
  );
}
