import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ReactNode } from "react";
import HeaderLogo from "src/images/SWapiLogo.png";

import styles from "@/styles/Home.module.css";

interface Props {
  children: ReactNode;
}

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Link href={"/"}>
          <Image src={HeaderLogo} alt="header" />
        </Link>
      </header>
      {children}
    </>
  );
}
