import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { ReactNode } from "react";
import { useQuery } from '@apollo/client'
import { ALL_CHARACTERS } from 'src/apollo/queries'
import FilmsImage from 'src/images/SWFilms.jpg'
import CharactersImage from 'src/images/SWCharacters2.jpg'
import SpeciesImage from 'src/images/SWSpecies2.png'
import HeaderLogo from 'src/images/SWapiLogo.png'
import ContentCard from '@/components/ContentCard'
import styles from '@/styles/Home.module.css'
import { style } from '@mui/system'

interface Props {
  children: ReactNode
}

export default function Layout({ children }: Props) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Link href={'/'}>
        <Image src={HeaderLogo} alt='header' />
        </Link>
      </header>
      {children}
    </>
  )
}
